<?php

namespace App\Models\Category;

use App\Models\Services\Service;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'category';
    protected $fillable = ['id', 'name_ar', 'name_en', 'image', 'created_at', 'updated_at', 'deleted_at'];
    protected $appends = ['image'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleted(function ($model) {
            SubCategory::where('category_id', $model->id)->delete();
            Service::where('sub_category_id', $model->id)->delete();
        });
    }


    public function subCategories()
    {
        return $this->hasMany(SubCategory::class);
    }

    public function getImageAttribute()
    {
        return !empty($this->attributes['image']) ? app_url('uploads/categories/' . $this->attributes['image']) : null;
    }

}
