<?php

namespace App\Models\Category;

use App\Models\Services\Service;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SubCategory extends Model
{
    use HasFactory,SoftDeletes;
    protected $table = 'sub_category';
    protected $fillable = ['category_id','name_en','is_popular','name_ar','image'];
    protected $appends = ['image'];

    public function category(){
        return $this->belongsTo(Category::class,'category_id','id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
           self::deleted(function ($model){
               Service::where('sub_category_id',$model->id)->delete();
           });
    }
    public function getImageAttribute()
    {
        return !empty($this->attributes['image']) ? app_url('uploads/subcategory/' . $this->attributes['image']) : null;
    }
}
