<?php

namespace App\Models\Item;

use App\Models\Order\MovementOrderItem;
use App\Models\Order\Order;
use App\Models\Services\Service;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $table = 'order_items';

    protected $guarded = [];
    protected $appends =['attachment'];

    public function order(){
        return $this->belongsTo(Order::class);
    }

    public function service(){
        return $this->belongsTo(Service::class);
    }
    public function getAttachmentAttribute()
    {
        return !empty($this->attributes['attachment']) ? app_url('uploads/attachment/'.$this->attributes['attachment']) :null;
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleted(function ($model){
            MovementOrderItem::where('order_item_id',$model->id)->delete();
        });
    }
}
